# Generated by Django 5.2.14 on 2026-05-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order", "label"], "verbose_name": "Categorie"},
        ),
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={"verbose_name": "Profil Employe"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date"], "verbose_name": "Commande"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["category", "name"], "verbose_name": "Produit"},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "Recette"},
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={},
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={"ordering": ["-date"], "verbose_name": "Revenue"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Stock"},
        ),
        migrations.AlterModelOptions(
            name="stocklog",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["number"], "verbose_name": "Table"},
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="estimated_time",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigne"),
                    ("en_route", "En route"),
                    ("arrived", "Arrive"),
                    ("delivered", "Livre"),
                    ("failed", "Echec"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("cuisine", "Cuisine"),
                    ("service", "Service"),
                    ("direction", "Direction"),
                    ("stock", "Stock"),
                    ("admin", "Administration"),
                ],
                default="service",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("onsite", "Sur place"),
                    ("delivery", "Livraison"),
                    ("takeaway", "A emporter"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("preparing", "En preparation"),
                    ("ready", "Pret"),
                    ("delivered", "Livre/Servi"),
                    ("cancelled", "Annule"),
                    ("paid", "Paye"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="required_qty",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="restaurant.stock"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="threshold",
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("g", "g"),
                    ("L", "L"),
                    ("cl", "cl"),
                    ("unite", "Unite"),
                    ("portion", "Portion"),
                ],
                default="unite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponible"),
                    ("occupied", "Occupee"),
                    ("reserved", "Reservee"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
