from django.urls import path
from . import views
urlpatterns = [
    path('',               views.home,           name='home'),
    path('login/',         views.login_view,     name='login'),
    path('logout/',        views.logout_view,    name='logout'),
    path('users/',         views.user_list,      name='user_list'),
    path('users/create/',  views.user_create,    name='user_create'),
    path('menu/',          views.menu_view,      name='menu'),
    path('products/',                 views.product_list,   name='product_list'),
    path('products/create/',          views.product_create, name='product_create'),
    path('products/<int:pk>/edit/',   views.product_edit,   name='product_edit'),
    path('products/<int:pk>/toggle/', views.product_toggle, name='product_toggle'),
    path('products/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('products/<int:product_id>/recipe/', views.recipe_manage, name='recipe_manage'),
    path('tables/',                    views.table_list,          name='table_list'),
    path('orders/',                    views.order_list,          name='order_list'),
    path('orders/create/',             views.order_create,        name='order_create'),
    path('orders/<int:pk>/',           views.order_detail,        name='order_detail'),
    path('orders/<int:pk>/status/',    views.order_update_status, name='order_status'),
    path('kitchen/',                   views.kitchen_view,        name='kitchen_view'),
    path('stock/',                views.stock_list,    name='stock_list'),
    path('stock/create/',         views.stock_create,  name='stock_create'),
    path('stock/<int:pk>/update/',views.stock_update,  name='stock_update'),
    path('stock/<int:pk>/history/',views.stock_history,name='stock_history'),
    path('hr/',              views.hr_dashboard,    name='hr_dashboard'),
    path('hr/<int:pk>/',     views.employee_detail, name='employee_detail'),
    path('hr/<int:pk>/edit/',views.employee_edit,   name='employee_edit'),
    path('dashboard/',     views.dashboard,     name='dashboard'),
    path('dashboard/api/', views.dashboard_api, name='dashboard_api'),
    path('order/', views.public_order_create, name='public_order_create'),
    path('order/confirm/<int:pk>/', views.public_order_confirm, name='public_order_confirm'),
]
